// <auto-generated />
using System;
using AT_PB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AT_PB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241002030956_InclusaoUsuario")]
    partial class InclusaoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AT_PB.Models.AnalisePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoReembolsoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoReembolsoId")
                        .IsUnique();

                    b.ToTable("AnalisesPedidos");
                });

            modelBuilder.Entity("AT_PB.Models.DespesaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoReembolsoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoDespesa")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoReembolsoId");

                    b.ToTable("DespesasMedicas");
                });

            modelBuilder.Entity("AT_PB.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoReembolsoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentoId");

                    b.HasIndex("PedidoReembolsoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("AT_PB.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoNotificacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("AT_PB.Models.PedidoReembolso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusPedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StatusPedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PedidosReembolso");
                });

            modelBuilder.Entity("AT_PB.Models.StatusPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusPedido");
                });

            modelBuilder.Entity("AT_PB.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AT_PB.Models.AnalisePedido", b =>
                {
                    b.HasOne("AT_PB.Models.PedidoReembolso", "PedidoReembolso")
                        .WithOne("AnalisePedido")
                        .HasForeignKey("AT_PB.Models.AnalisePedido", "PedidoReembolsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoReembolso");
                });

            modelBuilder.Entity("AT_PB.Models.DespesaMedica", b =>
                {
                    b.HasOne("AT_PB.Models.PedidoReembolso", "PedidoReembolso")
                        .WithMany("DespesasMedicas")
                        .HasForeignKey("PedidoReembolsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoReembolso");
                });

            modelBuilder.Entity("AT_PB.Models.Documento", b =>
                {
                    b.HasOne("AT_PB.Models.PedidoReembolso", "PedidoReembolso")
                        .WithMany("Documentos")
                        .HasForeignKey("PedidoReembolsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoReembolso");
                });

            modelBuilder.Entity("AT_PB.Models.Notificacao", b =>
                {
                    b.HasOne("AT_PB.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AT_PB.Models.PedidoReembolso", b =>
                {
                    b.HasOne("AT_PB.Models.StatusPedido", "StatusPedido")
                        .WithMany("PedidosReembolso")
                        .HasForeignKey("StatusPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AT_PB.Models.Usuario", "Usuario")
                        .WithMany("PedidosReembolso")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusPedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AT_PB.Models.PedidoReembolso", b =>
                {
                    b.Navigation("AnalisePedido");

                    b.Navigation("DespesasMedicas");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("AT_PB.Models.StatusPedido", b =>
                {
                    b.Navigation("PedidosReembolso");
                });

            modelBuilder.Entity("AT_PB.Models.Usuario", b =>
                {
                    b.Navigation("Notificacoes");

                    b.Navigation("PedidosReembolso");
                });
#pragma warning restore 612, 618
        }
    }
}
